version: '3.1'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terminal-portfolio
    ports:
      - "127.0.0.1:3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

  volumes:
    portfolio:

# it won't work unless you create a Dockerfile for it :)