version: '3.8'

services:
  terminal-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terminal-portfolio
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx/sites-available/terminal-portfolio.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

// it won't run unless you create the Dockerfile first :)