version: '3.3'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terminal-portfolio
    restart: unless-stopped
    ports:
      - "127:0.0.1:3000:3000"
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  portfolio-network:
    driver: bridge

# it won't work unless you create a Dockerfile for it :)